### ISSUE TITLE
Test compilation avec le publish addon

### ISSUE THREAD

**Issue by idealtitude** [idealtitude/shika_source#1]
Je viens de faire un test de compilation du jeu (avec le publish addon (nouvel addon de compilation des jeux, livré par défaut avec blender, cf prefs dans blender), voir doc en attachment): 

j'ai testé mon dossier source et la scene 0.55 de jb, l'exécutable produit par l'addon plante dans les deux cas, avec un magnifique "Erreur de segmentation (core dumped)", va falloir vérifier ce problème et le résoudre avant d'aller plus loin. 

Je pense fortement que cela vient de l'absence de texture de certains éléments, je referais un autre test donc pour en être sûr.. il est possible aussi que ce bug n'apparaisse pas sous windows...

Merci de me dire si vous reproduisez chez vous aussi ce bug...

Voici le card créé sur trello: https://trello.com/c/6Mb0NtwN/49-version-0-0-compilation-ok-executable-bug-cf-description-23-06-2015

**Comment by thibsert** [comment]
Pas de core dumped chez moi, mais des erreurs python

> ImportError: No module named 'bpy'

Idem en compilant "à l'ancienne" avec l'addon game_engine_save_as_runtime.

De mémoire, je ne crois pas qu'on puisse utiliser bpy en dehors de Blender... Si c'est confirmé, il va falloir revoir quelques scripts.

**Comment by idealtitude** [comment]
Ca c'est une bonne trouvaille tibo t'as bien fait de regarder ça! Tu utilises bpy de ton côté? Je vais regarder dans mes scripts comment le remplacer.

**Comment by thibsert** [comment]
Non je ne l'utilise pas. J'ai vu que tu t'en servais juste pour des histoires de path, ça devrait être facile à corriger je pense.
Une fois qu'on aura éliminé bpy, je pourrais vérifier si l'export en runtime fonctionne effectivement.

**Comment by idealtitude** [comment]
Dans mes scripts, je me sers de bpy pour la gestion des chemins, donc pour le remplacer je crois qu'on peut utiliser la méthode que j'ai employée dans saveload.py qui fonctionne parfaitement, ex.:

```
REAL_CWD = os.getcwd()
DB_PATH = REAL_CWD + os.sep  + 'saveload' + os.sep + 'shikabdd'
```

D'après mes vérifications je n'utilise pas bpy pour d'autres choses... Ce sera donc aisé à modifier.

Je tente ça.

**Comment by idealtitude** [comment]
Ayé c'est modifié, le jeu fonctionne normalement et os.getcwd fait son boulot donc bpy est remplacé dans mes scripts.

Plus qu'à attendre le résultat de ton test de compil...

**Comment by thibsert** [comment]
J'ai corrigé deux fautes de frappe ligne 35 dans mainblend.py
Mais main.blend reste bloqué sur "loading", et aucun message dans la console.
J'enquète.

**Comment by idealtitude** [comment]
Curieux j'ai pas ce souci... Qu'est-ce qui n'allait pas ligne 35?

**Comment by thibsert** [comment]
Ligne 35

> bge.logic.globalDict['curent_profil'] = self.datas['user_prefs']['current_profil']]
> #manque un r dans current, un ] en trop
> bge.logic.globalDict['current_profil'] = self.datas['user_prefs']['current_profil']

J'ai aussi du ajouter un appel à main() à la fin du fichier.

Je me demande si j'ai pas merdouillé avec git. Tu sais comment on annule le dernier pull ?

**Comment by idealtitude** [comment]
Ach, bien joué pour les corrections! Le coup du main() à la fin c'est une boulette de ma part, l'autre jour je l'ai enlevé pensant que le script était appelé en tant que module, j'avais zappé qu'on l'appelait en tant que script, donc en effet bien joué pour la correction!

Pour ce qui est d'annuler le dernier pull je ne sais pas du tout, je l'ai jamais fait. On va regarder la doc, je te dirais ce que j'ai trouvé.

**Comment by thibsert** [comment]
> git checkout --fichieràrestaurer

Bon maintenant j'arrive à compiler le jeu (j'ai mis un moment à comprendre qu'il fallait rentrer _chaque_ dossier dans asset path), mais au lancement j'ai cette erreur et le jeu se ferme :

> Error Totblock: 1

(Elle indique une fuite mémoire, et d'après ce que j'ai lu ce ne serait pas elle qui provoque le plantage - c'est une erreur "normale" de bge :-$ )

**Comment by idealtitude** [comment]
Ach zut... Je me renseigne sur ce message d'erreur.

**Edit** D'après ce post ça vient de blender lui-même en effet: http://blender.stackexchange.com/questions/15255/game-engine-error-totblock-1-memory-leak

**Comment by thibsert** [comment]
**Ça fonctionne**

Il faut copier tous les blends qui se trouvent à la racine, dans le dossier du bin. Il y a probablement moyen de trouver une manière plus élégante dans les paramètres de Publish Addon, mais dans l'idée c'est OK.

Je teste vite fait si j'arrive à lancer un level en mode runtime, avant qu'on puisse clore.

**Comment by idealtitude** [comment]
Oki génial tibo!! Bien joué! ;)

**Comment by thibsert** [comment]
Les levels fonctionnent aussi.

Open issues : 0

Je crois qu'on a été très bons aujourd'hui :-D

**Comment by idealtitude** [comment]
Excellent! C'est clair, on a été efficace today!! :)

**Comment by thibsert** [comment]
Par contre j'ai tout cassé mon dépot local :-(
Pas grave, je re-clone le tout et je repars sur du propre.

**Comment by idealtitude** [comment]
Lol ><

Oui tout à fait, c'est l'occase de repartir sur une base propre comme tu dis ;)
