### ISSUE TITLE
Erreur de segmentation lors du lancement de levels.blend

### ISSUE THREAD

**Issue by idealtitude** [idealtitude/shika_source#10]
**Erreur de segmentation (core dumped)**

Ca ne fonctionne plus du côté levels.blend, je viens d'essayer de le lancer après avoir pull tes mises à jour tibo.

Je vois pas trop où ça plante...

Voici le contenu du fichier levels.crash.txt généré par blender avant de quitter:

> # Blender 2.75 (sub 0), Commit date: 2015-06-10 15:39, Hash bff8b5d
# backtrace

./blender(BLI_system_backtrace+0x1d) [0x19f065d]
./blender() [0x102f435]
./blender() [0x102f612]
/lib64/libc.so.6() [0x3153c358f0]
./blender(_ZNSt8_Rb_treeIP20CcdPhysicsControllerS1_St9_IdentityIS1_ESt4lessIS1_ESaIS1_EE5eraseERKS1_+0x39) [0x1984d09]
./blender(_ZN21CcdPhysicsEnvironment26RemoveCcdPhysicsControllerEP20CcdPhysicsController+0x20) [0x1978720]
./blender(_ZN20CcdPhysicsControllerD1Ev+0x2b) [0x198f00b]
./blender(_ZN20CcdPhysicsControllerD0Ev+0x9) [0x198f109]
./blender(_ZN13KX_NearSensorD1Ev+0x31) [0x191cf11]
./blender(_ZN13KX_NearSensorD0Ev+0x9) [0x191cf69]
./blender(_ZN11SCA_IObjectD1Ev+0x35) [0x194b185]
./blender(_ZN23BL_DeformableGameObjectD0Ev+0x9) [0x18c1949]
./blender(_ZN8KX_Scene15NewRemoveObjectEP6CValue+0x3a1) [0x1911bd1]
./blender(_ZN8KX_Scene24RemoveNodeDestructObjectEP10SG_IObjectP6CValue+0x1c) [0x1911cbc]
./blender() [0x1911d55]
./blender(_ZN8KX_SceneD1Ev+0x57) [0x1912d87]
./blender(_ZN8KX_SceneD0Ev+0x9) [0x19131f9]
./blender(_ZN24KX_BlenderSceneConverter11RemoveSceneEP8KX_Scene+0x27) [0x18b78d7]
./blender(_ZN15KX_KetsjiEngine21RemoveScheduledScenesEv+0xa1) [0x18e0821]
./blender(_ZN15KX_KetsjiEngine22ProcessScheduledScenesEv+0x3c) [0x18e17dc]
./blender(_ZN15KX_KetsjiEngine9NextFrameEv+0x600) [0x18e1e20]
./blender() [0x18a7fe8]
./blender(StartKetsjiShell+0x1003) [0x18a91c3]
./blender() [0x10bbe14]
./blender() [0x104dc12]
./blender() [0x104ef9a]
./blender() [0x104f309]
./blender() [0x104f7d6]
./blender(wm_event_do_handlers+0x3be) [0x104fcee]
./blender(WM_main+0x18) [0x1037148]
./blender(main+0x52c) [0x1031e86]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x3153c21d65]
./blender() [0xf33f81]

**Comment by thibsert** [comment]
Je croyais qu'on laissait libload de côté pour le moment ?

**Comment by idealtitude** [comment]
C'est ce que j'allais te dire...  de toute façon faut reprendre la conception de levels.blend, vu qu'en effet libload semble plutôt devoir être abandonnée.

Je vais refaire de zero levels.blend et reécrire tout le script associé.

Ceci dit comment tu fais le lien entre ce bug et libload? A priori rien ne nous dit que ça vient de libload, aussi bien ça vient d'autre chose.

**Comment by thibsert** [comment]
Jusque là, on n'a constaté des segfault que lorsqu'on utilisait LibLoad.
LibLoad est réputée buggée.
Les levels fonctionnent si on les charge autrement.

Ça ne prouve rien, mais ça fait beaucoup d'indices qui vont dans le même sens.

Je sais pas si ça aide, mais en lançant blender en mode --debug, on obtient ces infos juste avant le crash (aucune idée de ce que ça veut dire) :

> Loaded !
> eval fcurve 'scale' - 0.000000 => 1/2, 0
> eval fcurve 'scale' - 0.000000 => 1/2, 0
> eval fcurve 'scale' - 0.000000 => 1/2, 0
> eval fcurve 'color' - 0.000000 => 1/2, 0
> eval fcurve 'color' - 0.000000 => 1/2, 0
> eval fcurve 'color' - 0.000000 => 1/2, 0
> eval fcurve 'color' - 0.000000 => 1/2, 0
> Writing: /tmp/levels.crash.txt
> Erreur de segmentation (core dumped)

**Comment by idealtitude** [comment]
Aucune idée non plus! :)

Comme tu dis pas mal d'indices pourraient nous laisser penser que ça vient de libload. Je ferme cet issue!
