### ISSUE TITLE
Problème de path

### ISSUE THREAD

**Issue by idealtitude** [idealtitude/shika_source#11]
Je m'en étais pas rendu compte, mais depuis qu'on a viré bpy pour la gestion des chemins, plus rien ne marche...

Voici un exemple avec le tout premier script appelé (scripts/mainblend.py), dont voici les premières lignes:

```
import sys
import os
import json

import bge


REAL_CWD = os.getcwd()
print(REAL_CWD)
CONFIG_FILE = REAL_CWD + os.sep + 'scripts' + os.sep + 'config.json'
print(CONFIG_FILE)
MAIN_MENU = REAL_CWD + os.sep + 'main_menu.blend'
PROFIL_SELECT = REAL_CWD + os.sep + 'profil_select.blend'
```

Et la console me renvoit évidemment ceci:

> Blender Game Engine Started
> /home/stef/Apps/blender
> /home/stef/Apps/blender/scripts/config.json
> Fichier de configuration introuvable à l'emplacement attendu! Game exit...
> Blender Game Engine Finished

Visiblement Blender considère (à juste titre) que le repertoire de travail est celui-ci d'où est appelé l'exécutable Blender, et non celui du jeu), d'où l'impossibilité pour lui de trouver les fichiers désirés...

Pour remédier à ça il faut changer le répertoire de travail de blender pour celui de la source du jeu... Reste à trouver comment faire ça...
Je vais chercher de mon côté

**Comment by idealtitude** [comment]
Problème résolu, il suffit d'ajouter `os.chdir(bge.logic.expandPath('//'))` après les imports pour se placer dans le répertoire de shika...

**Comment by thibsert** [comment]
Bien joué.
Le bug m'avait aussi échappé parce que j'ai l'habitude de lancer les blends depuis mon gestionnaire de fichier, et là le path est le bon.

**Comment by idealtitude** [comment]
Hi tibo :)

J'ai pris l'habitude de lancer blender depuis un terminal depuis qu'on est sur ce projet, on a guère le choix en effet si on veut avoir les infos nécessaires pour le débogage...

Halalala ces histoires de path! :warning:

**Comment by idealtitude** [comment]
Du coup heureusement que tu avais spoté le coup avec bpy, ça nous a permis de résoudre intelligemment nos histoires de path et du même coup d'appeler un module en moins (ce qui du point de vue de l'optimisation du jeu est toujours bon à prendre)!

**Comment by thibsert** [comment]
> on a guère le choix en effet si on veut avoir les infos nécessaires pour le débogage...

J'ai réglé le bouzin pour que les .blends s'ouvrent toujours depuis un terminal, évidement ;)

> et du même coup d'appeler un module en moins (ce qui du point de vue de l'optimisation du jeu est toujours bon à prendre)!

D'autant plus qu'entre temps sur le BC, on m' indiqué que bpy et moins performant qu'os pour ce genre d'opération (c'est assez logique remarque).

**Comment by idealtitude** [comment]
Oui c'est vrai, j'y avais pas pensé mais tu as parfaitement raison je pense, il est en effet tout à fait logique que os soit plus performant...

On le saura dorénavant...

Ps: j'ai pushé palpha sur le master, comme ça le master est à jour; quant à nous on continue bien sûr de bosser sur palpha :) Je me demandais l'autre jour d'ailleurs quelle était déjà la commande pour faire ce push, je crois que ce que tu m'avais proposé était juste... j'ai juste fait `git push origin palpha:master --force` (le force est nécessaire pour bypasser un pull obligatoire (et non désiré du reste en ce cas)).
