### ISSUE TITLE
Message d'erreurs dans conduite.blend

### ISSUE THREAD

**Issue by idealtitude** [idealtitude/shika_source#5]
Voici le retour de la console:

> Method SCA_ISensor.frequency is deprecated, please use SCA_ISensor.skippedTicks instead.
> /home/stef/Dev/SHIKA/SOURCE/shika_test/shika_source/conduite.blend/emitter.py:12

**Comment by thibsert** [comment]
corrigé, normalement
https://github.com/idealtitude/shika_source/commit/a95f05e8e544f036e500ad4ad862df624a1ef538

**Comment by idealtitude** [comment]
Effectivement, ai testé le fichier tracks/map_test1.blend, l'erreur a disparu. Je ferme cette issue..

Par contre il y a un nouveau message d'erreur que je n'avais pas constaté auparavant:

> Python module can't be imported - object 'smoke', controller 'Python':
> ImportError: No module named 'emitter'

Il faudra ouvrir une nouvelle issue...

**Comment by idealtitude** [comment]
Je réouvre l'issue, après test du fichier tracks/map_test_2.blend (branch test), la console me renvoie ceci!

> Python script error - object '000_SAVELOAD_TEST', controller 'Python':
> Traceback (most recent call last):
>  File "conduite_saveload_test.py", line 9, in <module>
> ImportError: No module named 'saveload'
> Method SCA_ISensor.frequency is deprecated, please use SCA_ISensor.skippedTicks instead.
> /home/stef/Dev/SHIKA/SOURCE/shika_test/shika_source/tracks/map_test_2.blend/emitter.py:12

Par rapport au message `ImportError: No module named 'saveload'`, ça vient du fait que le fichier map_test_2.blend, ne peut pas trouver le module saveload, étant placé dans tracks/
Faudra faire l'import du module à partir d'un blend situer à la racine (cf demosaveload.blend pour un exemple d'import et d'utilisation de saveload)...

Pour la question SCA_ISensor ça ne devrait pas être compliqué à corriger...

**Comment by thibsert** [comment]
J'ai retiré la génration de fumée, qui était juste un essai.
Mais j'ai toujours des problèmes pour charger les modules s'ils ne sont pas dans le même dossier que le blend, il faudrait que tu m'expliques ça Steph. L'ideal serait de dire à Python que tous les modules se trouvent dans //./scripts, mais je ne sais pas comment faire.

**Comment by idealtitude** [comment]
Ok tibo, je regarde comment fixer ce souci dès que possible!

**Comment by idealtitude** [comment]
tibo, jte confirme qu'avec la commande os.chdir (dont je t'ai parlée hier) on peut se déplacer dans le bon répertoire de travail; le but dans nôtre cas c'est de nous déplacer là où python est censé trouver le module...

J'ai fais un test à partir de tracks/map_test1.blend, j'ai lié un empty dans la scène à deux scripts (path_hack.py (pour résoudre les chemins), et scripts/conduit_saveload_test.py (pour effectuer le test d'import ) à proprement parler)). J'ai juste modifié ainsi dans conduite_saveload_test.py les lignes suivantes:

```
sys.path.append('../..')

print(os.getcwd())

os.chdir('../')

print(os.getcwd())
```

Et voici le retour de la console:

> Blender Game Engine Started
> /home/stef/Dev/SHIKA/SOURCE/shika_test/shika_source/tracks
> /home/stef/Dev/SHIKA/SOURCE/shika_test/shika_source
> Python script error - object '000_Test_SaveLoad', controller 'Python':
> Traceback (most recent call last):
>   File "conduite_saveload_test.py", line 16, in <module>
> 
> ImportError: No module named 'saveload'

---

On progresse, mais je ne comprends pas pourquoi il ne trouve pas le module, on est dans le bon répertoire de travail pourtant, c'est à dire à la racine, là où est présicément le module... Mystère!

Si j'arrive pas à résoudre ça, faudra qu'on déplace (voir copie) le module dans le répertoire qui conviendra à python (ou a blender... je ne sais pas du coup de qui vient le souci !). Faudra que je modifie le module en conséquence aussi...

**Comment by idealtitude** [comment]
Il me semble que je progresse... J'ai modifié scripts/conduite_saveload_test.py, tout au début:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os

os.chdir('../')
sys.path.append('saveload')

import bge
from saveload import saveload as sl
```

Et la console me renvoie maintenant:

> Blender Game Engine Started
> Python script error - object '000_Test_SaveLoad', controller 'Python':
> Traceback (most recent call last):
>   File "conduite_saveload_test.py", line 11, in <module>
> 
> ImportError: cannot import name 'saveload'

Ca veut dire qu'on se rapproche du but... Je continues à chercher

**Comment by idealtitude** [comment]
J'ai pushé mes derniers tests car il s'avère qu'ils fonctionnent... Problème résolu! 

Fichiers modifiés et corrigés:
- modified:   saveload/saveload.py
- modified:   scripts/conduite_saveload_test.py
- modified:   scripts/users.json
- modified:   tracks/map_test_1.blend

Avant de fermer cette issue, j'attends tes retours! :)

Pour tester donc lance tracks/map_test1.blend

**Comment by thibsert** [comment]
map_test1 fonctionne bien chez moi, et j'ai réussi à utiliser saveload dans test_map2 donc je pense qu'on peut clore le bug et valider la méthode. À noter qu'il faut aussi lancer path_hack.py pour que ça fonctionne, et même dans l'idéal le lancer avant d'utiliser saveload (ou l'inclure dans le script avant os.chdir(), ça fonctionne aussi).
Bien joué :)

**Comment by idealtitude** [comment]
Oui effectivement je te disais 2 messages plus haut qu'il faut utiliser path_hack.py ...

Je ferme l'issue! :)

**Comment by idealtitude** [comment]
J'avais pas relevé ce que tu disais à propos d'inclure path_hack dans le script... Ca pourrait être un moyen d'utiliser un fichier en moins, l'inconvénient c'est qu'au lieu d'avoir un seul fichier pour cette fonction, qu'on appelle au besoin, on serait obligé de le rajouter dans touts les scripts où on veut l'utiliser. L'un dans l'autre je ne sais lequel est le plus proffitable...

Qu'en penses-tu de ton côté tibo? Est-ce que ça vaut le coup?

Sinon j'ai fait du ménage à quelques endroits (demande-moi si u as besoin de précision), et j'ai également ajouté des beeps audio sur les boutons des menus.
En outre j'ai discuté avec ena de l'écran zoo (accessible directement depuis le menu principaal en clickant sur play... Dans cet écran on a une scène que ena va moder donc, cette scène est une vue 3d du zoo, manipulable à la souris (rotation, zoom), chaque zone de la vue du zoo conduit à d'autres écrans (courses, marché noir, autre?). Ce qui va nous permettre d'impémenter progressivement tous les écrans à venir du jeu (dont notamment les courses)... 

Voilà pour le news du jour... Et de ton côté quoi de neuf?

**Comment by thibsert** [comment]
> Qu'en penses-tu de ton côté tibo? Est-ce que ça vaut le coup?

Non tu as raison il servira sans doute ailleurs, autant le laisser séparé

> Voilà pour le news du jour... Et de ton côté quoi de neuf?

Je m'y remets doucement ;)

**Comment by idealtitude** [comment]
> Je m'y remets doucement ;)

Sweet! :)
