### ISSUE TITLE
bug dans le menu

### ISSUE THREAD

**Issue by thibsert** [idealtitude/shika_source#6]
Lancer main.blend
Choisir un profil
Cliquer sur jouer

Cliquer là où se trouvaient les boutons "Jouer", "Options", "Quitter" : ils sont encore actifs (son + print dans la console) alors qu'on ne les voit plus

Ubuntu
Blender 2.75rc2

**Comment by idealtitude** [comment]
J'y ai cogité un peu cet aprem, j'envisage quelques solutions en gérant les différentes scenes du blend plus dynamiquement, je vais tester tout ça.

**Comment by idealtitude** [comment]
Bon j'ai finalement cogité à une solution: rendre les boutons actifs uniquement lorsqu'aucune autre scène n'est chargée. C'est vrai que j'ai prévu de gérer la plupart des actions disponibles dans le menu avec des overlay scenes, de manière à garder de la fluidité dans cet écran et éviter un chargement à chaque fois.

Je vais modifier le script en conséquence donc, et si ça fonctionne comme je l'espère on pourra clore cet issue.

**Comment by idealtitude** [comment]
Ayé, corrigé! Je ferme.
