### ISSUE TITLE
test de sqlite3 sous windows

### ISSUE THREAD

**Issue by thibsert** [idealtitude/shika_source#7]
Avis à tous ceux qui sont sous Windows, nous aurions besoin que vous essayez la manip suivante. Ça nous permettrait de savoir si on peut utiliser sqlite3 pour le système de sauvegarde, ou si on doit se contenter d'un système moins pratique, bref ça nous aiderait vraiment.

Télécharger cette archive et la décompresser :
https://drive.google.com/file/d/0BwMdZN1TuwICdm1zY0hrWnJKRGM/view?usp=sharing
Ouvrir main.blend et presser P

Si un message ressemblant à "[{'id': 1, 'argent': 100, 'date': '2015-06-19 22:03:57',]" s'affiche dans Blender et dans la console, c'est gagné.
Si rien ne s'affiche dans Blender, et/ou qu'une erreur s'affiche dans la console, c'est perdu.

Dans les deux cas, merci d'indiquer le résultat affiché, votre version de Blender, votre version de Windows, votre version de Python (si installé).

**Comment by thibsert** [comment]
Résultat : ça fonctionne, le message s'affiche dans Blender et dans la console
Blender 2.75rc2
Windows 8.1 64bits
Python pas installé

**Comment by the3dena** [comment]
Résultat : fonctionne dans Blender + console
Blender 2.71
Windows 7 - 64bits
Python 2.6.2

**Comment by thibsert** [comment]
Fonctionne chez Theo
Blender 2.75
Windows ?

**Comment by idealtitude** [comment]
Bon ben c'est génial, je crois qu'on est pas loin de pouvoir clore l'issue.... A toi d'en décider tibo, tu es l'assignee ce celui-ci! :)

En tous cas on a trouvé une solution (et rapidement en plus), et ça va être super côté optimisation du jeu en ce qui concerne la gestion des datas...

Bon plus qu'à m'atteler au codage du module saveload version sqlite, ça va être cool!! :) on a presque tout, ça ira vite, on a aussi juste besoin de savoir si on peut valider le schema de la bdd! à voir donc avec jb si tout est ok, ensuite j'attaque le boulot (c'est d'autant plus cool que ça va nous permettre de nous lancer sur toute la dynamique du jeu (navigation, courses, améliorations...); j'attends ton feu vert donc tibo! ;)

Le schema actuel de la bdd: https://drive.google.com/open?id=1qkAWkR5cr1bKNwgC0c4Ld1IV14mSF5UUYvjOxmO_kLc

**Comment by thibsert** [comment]
C'est parfait tout ça, merci Ena et Theo pour le test. Steph, à toi de jouer pour la suite ;)
