### ISSUE TITLE
Problème de chargement des actions du fichier map_test_2.blend

### ISSUE THREAD

**Issue by idealtitude** [idealtitude/shika_source#8]
Je suis en train de procéder à la mise en place de la logique dans le fichier levels.blend, voir donc également le fichier associé levels.py

Au démarrage du fichier levels.blend on effectue un routage (en fonction des variables de sessions contenu dans le globaldict) et on charge depuis tracks/ le level correspondant à la requête du joueur...

Le chargement se fait de façon asynchrone, avec le module libload de l'api blender, de manière à avoir un écran de chargement dynamique, puis lorsque le chargement est achevé j'enlève la scene principal de levels.blend et charge à la place la scene principal du track chargé (fichiers blend dans le répertoire tracks)...
Jusque là tout va bien!

**BUG** Par contre il y a un echec lors du chargement de certains actions (toutes?) du track chargé et avec un script apparemment; voici en exemple le retour de la console (dans ce test le track chargé est tracks/map_test_2.blend):

> Python script error - object 'hud', controller 'Python':
> Traceback (most recent call last):
>   File "hud", line 20, in <module>
> NameError: name 'player' is not defined
> Failed to load action: compteurVitesse
> Failed to load action: rocketreload
> Failed to load action: LifeBar
> Failed to load action: blades_rotation

Il s'agit d'un problème à résoudre donc...

**Important** En outre, et c'est important, il faut se mettre d'accord sur une convention de nommage de la scene principale de chaque track afin de rendre aisée la manip de basculement entre la scene du loader (dans levels.blend) et la scene principale du tracks chargé. Ainsi dans vos blends vous devrez donc dans level1 nommer la scene principale par exemple 'level1_main_scene', dans le level 2 ce sera 'level2_main_scene', etc...

**TODO** Pour animer la barre de progression (créée avec bgui), je récupère au fur et à mesure que libload les envoie, les données sur la progression du chargement du blend... Mais il se trouve que ce n'est pas du tout fiable... en tous cas pour l'instant; j'ai vu sur un topic dans blender artists que d'autres rencontrent le même problème ([voir ici pour la discute](http://blenderartists.org/forum/showthread.php?308162-How-to-use-LibLoad-LibNew-LibFree-etc-for-load-objects-and-more)). Donc on avisera et si on n'a pas de solutoon satisfaisante, je remplacerai la barre de progression par un indicateur quelconque (une anim de chargement qui tourne en boucle... reste à définir quoi).

**Veille** A surveiller: j'ai eu plusieurs fois des erreurs de segmentation en testant le track une fois chargé! Difficile d'analyser d'où vient le problème... 

---

Voilà, je pense avoir fait le tour pour cet issue...

**Comment by thibsert** [comment]
> Failed to load action: compteurVitesse
> Failed to load action: rocketreload
> Failed to load action: LifeBar

Ces actions font partie de la scene HUD. Cette scène est en travaux, elle n'a rien à faire dans les fichiers des maps : elle devrait être soit dans level.blend, soit chargé dynamiquement depuis un autre blend. Si on la met dans levels.blend, ce qui parait assez logique, ça résoud le problème.

> Failed to load action: blades_rotation

Ça par contre ça m'inquiète beaucoup. Cette anim est dans kart_model1.blend, dans le groupe "player", qui est linké dans la map et je ne vois pas bien comment faire autrement. Et par la suite on en aura plein d'autres qui seront dans le même cas : les anims des pièges, des monstres, de maskito etc. Il faut résoudre ça de toute urgence.

À noter que Libload est réputée bugguée de partout (de l'aveu des devs du bge). Mais qu'on n'a pas vraiment d'autre solution pour charger dynamiquement des choses...

>  Ainsi dans vos blends vous devrez donc dans level1 nommer la scene principale par exemple 'level1_main_scene', dans le level 2 ce sera 'level2_main_scene', etc...

De mon point de vue il ne devrait y avoir qu'une Scene dans chaque level, avec toujours le même nom (disons "main"), ce qui simplifie ton code.

_edit : libload a un paramètre load_actions qui est False par défaut. Mais le passer à True ne suffit pas à résoudre le problème_

**Comment by thibsert** [comment]
J'ai réussi à faire fonctionne l'anim en la liant manuellement dans levels.blend. Mais je ne trouve pas que ça soit une bonne solution, il faudra le faire pour toutes nos anims et ça n'a aucune logique.

Par contre, une solution simple serait de ranger toutes nos maps dans le fichier levels.blend, chacune dans une scène. Comme ça pas besoin d'utiliser libload, il suffit de changer la scène active.

**Comment by thibsert** [comment]
Je crois que j'ai trouvé un contournement qui fonctionne bien et qui me semble satisfaisant.

Dans levels.blend, linker à la main (avec file/link) les scènes contenues dans les blends de /tracks.
Dans levels.py, changer la scène active avec scene.replace()
C'est simple et ça fonctionne :-)

**Comment by idealtitude** [comment]
Intéressant! Par contre ça serait bien de tenter d'obtenir de l'aide avant de se rabattre sur une solution bidouille... Tu parlais de poser la question sur le BC, ça pourrait valoir le coup! Essayons ça...

**Comment by idealtitude** [comment]
J'ai une autre question aussi qui peut être une très bonne piste à creuser: est-ce que c'est l'entiereté des actions qui est concernée par ce problème où juste certaines seulement qui ne sont pas chargées? Si c'est le deuxième cas il y a sûrement moyen de déterminer pourquoi le chargement échoue... dès lors on pourrait agir en conséquence.

Je vais me créer un compte sur blender artists (j'en avais un il y a longtemps, mais quasiment jamais utilisé), comme ça on recherche parallèlement de l'aide du côté du bc pour toi, et sur ba de l'autre pour moi...

**Comment by thibsert** [comment]
Je ne sais pas, on n'a que ces quelques actions pour le moment. Mais j'ai bien l'impression qu'elles sont toutes concernées.
Si tu fais un blend d'exemple pour BA, tu pourras me le passer pour le BC ?

**Comment by idealtitude** [comment]
Oki pour le blend, je suis en train de rédiger mon post là, je t'enverrai le lien que tu puisses suivre la discute.
Par contre il serait bien de svaoir si c'est toutes les actions qui sont concernées ou pas... Je pense que cette question me sera posée.

**Comment by thibsert** [comment]
Pour autant que je sache elles sont toutes concernées.

**Comment by idealtitude** [comment]
Okay

**Comment by idealtitude** [comment]
Tiens pour info, c'est pas le même problème mais c'est relatif à la question... et si jamais ça se produit pour nous on saura où chercher:

https://developer.blender.org/T45267

Sinon, je me suis créé un compte sur BA, et j'ai posté ma demande d'aide, mais ils modèrent avant de publier... En attendant voici ma page de profil, tu pourras certainement y trouver mon post quand il aura passer la modération, s'il la passe... mais espérons qu'il n'y ai pas de souci.

http://blenderartists.org/forum/member.php?248625-idealtitude

**Comment by idealtitude** [comment]
Et voici le topic qui a donc passé la modération:

http://www.blenderartists.org/forum/showthread.php?376048-LibLoad-failed-to-load-actions-is-it-a-problem-with-the-tree-of-the-project&highlight=

**Comment by idealtitude** [comment]
Bon après des tests et une relecture du code dans le blend map_test_2.blend il se trouve que c'est le script hud qui est bugué, des modifs faites dans les modés n'ont pas été répercutées dans le script, ce qui fait que blender ne s'y retrouve pas... J'ai essayé de corriger le script mais san succès, et après en avoir discuté avec l'intéressé, il m'a conseillé de récrire le script... Donc je te propose tibo, qu'on reprenne l'histoire du hud.

Ca te dit de t'en occuper vu que c'est dans ta partie...?

**Comment by idealtitude** [comment]
Je ne parviens toujours pas à trouver pourquoi les actions ne sont pas chargées, je me demande s'il ne faudrait pas repenser la partie hud et le code associé. Ce qu'a fait jb marche très bien, mais on a visiblement un problème avec libload qui ne semble pas trouver les actions... jb me disait que libload écrase les scenes, peut-être qu'effectivement il y a une incompréhension de ce côté...
Je vais continuer à creuser cette piste.

**Comment by thibsert** [comment]
> il se trouve que c'est le script hud qui est bugué

ça ne se limite pas au script du HUD, puisque l'action blades_rotation est appelée par une brique logique. Je peux le réécrire, mais pour jouer des actions il n'y a à pas 50 méthodes, et aucune ne semble fonctionner.

**Comment by idealtitude** [comment]
Ach... il doit bien y avoir moyen de résoudre cette difficulté. Le gras qui m'a répondu sur BA me disait d'utiliser les paramètres supplémentaires de libload lors de l'appel (comme laod_action=True), mais ça ne change rien, car le problème ne semble pas venir de là.

**Comment by idealtitude** [comment]
Ce qui est bizzare c'est qu'il trouve tout sauf les actions.

Une question en passant, dans le script hud de jb, il y a ça:

```
kart = scene.objects["kart"]

player = scene.objects["player"].groupMembers['player']
```

Si je comprends à quoi fait référence la variable player, et le groupe associé (qu'on retrouve dans le outliner), je ne vois pas en revanche quel est l'objet appelé kart et que je n'ai pas réussi à voir dans le outliner...

As-tu quelques infos à ce sujet?

**Comment by idealtitude** [comment]
Je pense à une éventuelle solution tibo, dis-moi ce que tu en penses:

tout à l'inverse de ta proposition de mettre tous les levels dans levels.blend, on pourrait mettre juste le kart (ou des karts si l'utilisateur en a plusieurs), et il suffirait de charger alors la map du level en cours...

**Comment by thibsert** [comment]
> kart = scene.objects["kart"]

C'est le modèle (mesh) du kart, dans kart_model1.blend.

> tout à l'inverse de ta proposition de mettre tous les levels dans levels.blend, on pourrait mettre juste le kart (ou des karts si l'utilisateur en a plusieurs), et il suffirait de charger alors la map du level en cours...

C'est plutôt logique quand on y pense. Mais il faudra bien, dans notre scene map, placer un empty par exemple et charger le kart à son emplacement. Avec Libload ? On tourne en rond non ?

Et je ne propose pas (plus) de mettre les levels dans levels.blend, mais de les lier, c'est tout à fait différent.

**Comment by idealtitude** [comment]
**/!\ En faisant un append des actions dans levels.blend, je fais disparaître les erreurs sur les actions!**

On se approche du but! Par contre j'ai toujours des erreurs:

> Python script error - object 'hud', controller 'Python':
> Traceback (most recent call last):
>   File "hud", line 19, in <module>
> NameError: name 'player' is not defined
> warning: scene Hud already exists, not added!
> Failed to load action: blades_rotation

As-tu une idée d'ou viennent ces erreurs?

---

**Edit**

> Et je ne propose pas (plus) de mettre les levels dans levels.blend, mais de les lier, c'est tout à fait différent.

Autant pour moi, j'avais cru comprendre que tu voulais placer toutes les maps dans des scènes différentes...

**Comment by thibsert** [comment]
C'est ce que j'écrivais [ici](https://github.com/idealtitude/shika_source/issues/8#issuecomment-120761137), on peut d'ailleurs les linker plutôt que les append. Honnêtement je trouve ça très sale (il va falloir le faire pour chaque action de chaque blend, penser à ajouter les nouvelles, etc). Mais c'est un workaround qui fonctionne.

> As-tu une idée d'ou viennent ces erreurs?

Le script du hud n'est pas propre, pour communiquer entre les scènes on devrait utiliser sendMessage() ou le globalDict qui servent à ça, et certainement pas référencer des objets selon leur nom. Ça fait partie des choses que je comptais réécrire.

[Question posée sur le Blenderclan](http://blenderclan.tuxfamily.org/html/modules/newbb/viewtopic.php?post_id=538233#forumpost538233)

**Comment by idealtitude** [comment]
Ok theo, donc sur cette question on attend ta reécriture du hud pour aller plus loin?!

Si oui, du coup je vais retourner m'occuper du module saveload! Il me faudrait d'ailleurs tes retours sur les derniers travaux.

**Comment by thibsert** [comment]
Encore une fois le problème ne se limite pas au HUD (->action blades_rotation).
Mais dans la mesure où on a différentes solutions de contournement, et où on attend les réponses des forums, je suis ok pour laisser ça en suspens.
Je regarde saveload.

**Comment by idealtitude** [comment]
Oui c'est vrai que y a ces autres soucis aussi... Ok donc on laisse en suspend...

**Comment by idealtitude** [comment]
Fermons cet issue aussi du coup, ça nettoie.
