### ISSUE TITLE
erreur dans saveload.py

### ISSUE THREAD

**Issue by thibsert** [idealtitude/shika_source#9]
Il y a un souci dans la classe read_table de saveload.py. Quand on fournit un userid=0, tout se passe bien. Quand on fournit un userid spécifique, on mange une erreur :

> Traceback (most recent call last):
>   File "conduite_saveload_test.py", line 17, in <module>
>   File "saveload/saveload.py", line 57, in read_table
>     cur.execute(query)
> sqlite3.OperationalError: no such column: id

L'erreur vient de la la ligne 51 : 

``` python
user = ' where id = %s' % iduser
#qu'on peut corriger facilement :
user = ' where iduser = %s' % iduser
```

**Comment by idealtitude** [comment]
Réessaie, c'était une faute de frappe de ma part, comme indiqué dans le message d'erreur, ce n'est pas id mais iduser...

Le problème doit donc être résolu, tu me diras.

**Comment by idealtitude** [comment]
Oui voilà t'as trouvé! ;)
